name: Bazel build

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  # typically used for bazel internal testing: changes outputRoot, sets idletimeout to ~15s
  TEST_TMPDIR: /tmp/bazel

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
  push:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        # action runners have bazelisk: - uses: bazelbuild/setup-bazelisk@v2
        # https://github.com/bazelbuild/bazel/issues/11062
      - run: mkdir -p "${TEST_TMPDIR}"
      - run: env | sort
      - name: Mount bazel cache  # Optional
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
        with:
          # needs to be an absolute path, not a variable; I've made it match TEST_TMPDIR above
          path: /tmp/bazel
          key: _bazel_runner
      - run: bazel build //...
      #- run: bazel test //... --test_output=errors --test_summary=detailed
